---
apiVersion: v1
kind: Secret
metadata:
  namespace: resto-nestjs-postgres-api-namespace
  name: registry-secret
stringData:
  .dockerconfigjson: |
    {"auths":{"registry.gitlab.com":{"auth":"AUTH_SECRET_KEY"}}}
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  namespace: resto-nestjs-postgres-api-namespace
  name: nestjs-kubernetes-secret
stringData:
  REDIS_PASSWORD: REDIS_PASSWORD
  POSTGRES_PASSWORD: postgres
  REDIS_URL: redis://:REDIS_PASSWORD@redis-service:6379
  POSTGRES_URL: postgres://postgres:POSTGRES_PASSWORD@resto-postgres-service:5432/nestjs
type: Opaque