apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: resto-nestjs-postgres-api-namespace
  name: nestjs-kubernetes-volume
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi